# Generated by Django 5.1.1 on 2024-10-01 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Command',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=20)),
                ('locator', models.CharField(max_length=200)),
                ('locatorVal', models.CharField(max_length=200)),
            ],
        ),
    ]
