# Generated by Django 5.1.1 on 2024-10-02 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brennadjango', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Set',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(default=0, max_length=36)),
                ('name', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=1000)),
                ('url', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='command',
            name='stepID',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='command',
            name='uid',
            field=models.CharField(default=0, max_length=36),
        ),
    ]
