# Generated by Django 5.1.1 on 2025-07-17 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brennadjango', '0002_set_command_stepid_command_uid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='command',
            old_name='locatorVal',
            new_name='action_val',
        ),
        migrations.RenameField(
            model_name='command',
            old_name='stepID',
            new_name='step_id',
        ),
        migrations.AddField(
            model_name='command',
            name='locator_val',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='command',
            name='set_uid',
            field=models.CharField(default=0, max_length=36),
        ),
    ]
