# Generated by Django 6.0.6 on 2026-06-12 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('brennadjango', '0003_rename_locatorval_command_action_val_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='command',
            old_name='set_uid',
            new_name='set_id',
        ),
        migrations.RemoveField(
            model_name='command',
            name='uid',
        ),
        migrations.RemoveField(
            model_name='set',
            name='uid',
        ),
    ]
