# Generated by Django 6.0.6 on 2026-06-16 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brennadjango', '0004_rename_set_uid_command_set_id_remove_command_uid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='command',
            name='status',
            field=models.CharField(default=(0,), max_length=200),
        ),
    ]
